apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath: 
    path: /kafka/kafka
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka-zookeeper
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath: 
    path: /kafka/kafka-zookeeper
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka-zookeeper-2
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath: 
    path: /kafka/kafka-zookeeper-2
